// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async esSearch(conn: ConnInput, index: string, dsl: JsonValue) : Promise<Result<SearchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("es_search", { conn, index, dsl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async esGetDoc(conn: ConnInput, index: string, id: string) : Promise<Result<Hit | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("es_get_doc", { conn, index, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async esListIndices(conn: ConnInput) : Promise<Result<IndexInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("es_list_indices", { conn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async esClusterHealth(conn: ConnInput) : Promise<Result<ClusterInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("es_cluster_health", { conn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async esFieldCaps(conn: ConnInput, index: string) : Promise<Result<Field[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("es_field_caps", { conn, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async esTestConnection(conn: ConnInput) : Promise<Result<TestResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("es_test_connection", { conn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCredential(connId: string, secret: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_credential", { connId, secret }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCredential(connId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_credential", { connId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Bucket = { key: string; count: number }
export type CausedBy = { type: string; reason: string }
export type ClusterInfo = { health: string; version: string; nodes: number }
/**
 * Connection metadata passed from the frontend (never the secret).
 */
export type ConnInput = { id: string; host: string; auth: string; user: string }
export type EsError = { type: string; reason: string; status: number; index?: string | null; shard?: number | null; node?: string | null; causedBy?: CausedBy | null }
export type Field = { f: string; t: string }
export type Hit = { _id: string; _index: string; _score: number | null; _source: JsonValue }
export type IndexInfo = { name: string; docs: number; health?: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type SearchResult = { total: number; took: number; hits: Hit[]; buckets?: Bucket[] | null; groupByField?: string | null; docCount?: number | null; error?: EsError | null }
export type TestResult = { ok: boolean; tookMs: number; version?: string | null; nodes?: number | null; health?: string | null; message?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
